#!/usr/bin/env python
# $Hg: urlbatcher,v$

from urlregex import urlbatcher
from urlregex.Urlcollector import UrlcollectorError

try:
    up = urlbatcher.Urlbatcher()
    up.argParser()
    up.urlSearch()
except (urlbatcher.UrlbatcherError, UrlcollectorError), e:
    urlbatcher.userHelp(e)
except KeyboardInterrupt:
    print
    pass
